### PR TITLE
Mention how to compile the Haskell code.

### PR DESCRIPTION
**Pull request by athas**

### CODE REVIEW

**Comment by kfl** [comment]
Looks good. I should probably add that to the makefile.

**Comment by athas** [comment]
Ken Friis Larsen notifications@github.com writes:

> Looks good. I should probably add that to the makefile.

You have no Makefile targets for the Haskell code.

I tried adding some, but you picked the same basenames for the SML and
Haskell implementations.

## 

\  Troels
/\ Henriksen

**Comment by kfl** [comment]
I know, that's why I stopped last time :wink: 

I decided that the Right Way :tm: would be to make a cabal file, which per default would put the Haskell binaries in a subdirectory. But then I got sucked into cabal and never finished.

These days, I'm thinking that would just put them into a subdir called, say, `hbin` or something.

**Comment by athas** [comment]
Ken Friis Larsen notifications@github.com writes:

> I know, that's why I stopped last time :wink: 
> 
> I decided that the Right Way :tm: would be to make a cabal file, which
> per default would put the Haskell binaries in a subdirectory. But then
> I got sucked into cabal and never finished.
> 
> These days, I'm thinking that would just put them into a subdir
> called, say, `hbin` or something.

I would just create distinct filenames and write a normal Makefile.
There is no need for Cabal.

## 

\  Troels
/\ Henriksen

**Pull request merged**
